#! /usr/bin/env python
# encoding: utf-8

bld.program(
    features="cxx test",
    source=["ranbo_tests.cpp"] + bld.path.ant_glob("src/*.cpp"),
    target="ranbo_tests",
    use=["ranbo_includes", "gtest"],
)
