#! /usr/bin/env python
# encoding: utf-8

bld.program(
    features="cxx",
    source="bit_occurrences.cpp",
    target="bit_occurrences_example",
    use=["ranbo_includes"],
)

bld.program(
    features="cxx",
    source="hello_world.cpp",
    target="hello_world_example",
    use=["ranbo_includes"],
)
