name: Build Kernel Example
on:
  workflow_dispatch:
    inputs:
      extra_resolve_options:
        description: "Extra Resolve Options"
        required: false
  schedule:
    - cron: "0 1 * * *" # 3 AM CET
  push:
  pull_request:
env:
  EXTRA_RESOLVE_OPTIONS: ${{ github.event.inputs.resolve_options }}
jobs:
  kernel_example:
    strategy:
      fail-fast: false
      matrix:
        config:
          - container: conanio/gcc8
            name: Kernel 4.15.0
            kernel_version: 4.15.0-144-generic
            kernel_path: /lib/modules/4.15.0-144-amd64/build
          - container: conanio/gcc10
            name: Kernel 5.4.0
            kernel_version: 5.4.0-74-generic
            kernel_path: /lib/modules/5.4.0-74-amd64/build
          - container: conanio/gcc10
            name: Kernel 5.8.0
            kernel_version: 5.8.0-53-generic
            kernel_path: /lib/modules/5.8.0-53-amd64/build
          - container: conanio/gcc10
            name: Kernel 5.13.0
            kernel_version: 5.13.0-30-generic
            kernel_path: /lib/modules/5.13.0-30-amd64/build
    runs-on: [self-hosted, docker, builder]
    name: ${{ matrix.config.name }}
    container:
      image: ${{ matrix.config.container }}
      options: --user 0:0
      volumes:
        - /home/buildbot/.ssh:/root/.ssh
    steps:
      - name: Install SSH client and Linux Headers
        run: apt clean && apt update && apt -y install openssh-client linux-headers-${{matrix.config.kernel_version}}
      - name: Checkout source code
        uses: actions/checkout@v2
      - name: Waf Configure
        run: python3 waf configure --git_protocol=git@ $EXTRA_RESOLVE_OPTIONS
      - name: List Modules directory
        run: ls -d /lib/modules/
      - name: Waf Build
        run: |
          echo "::add-matcher::.github/gcc-problem-matcher.json"
          python3 waf --kernel_example --kernel_path=${{ matrix.config.kernel_path }}
