name: PlatformIO
"on":
  workflow_dispatch:
    inputs:
      extra_resolve_options:
        description: Extra Resolve Options
        required: false
  schedule:
    - cron: 0 1 * * *
  push:
    branches:
      - master
  pull_request:
jobs:
  platformio:
    name: PlatformIO Build
    runs-on:
      - self-hosted
      - docker
      - builder
    container:
      image: ghcr.io/steinwurf/platformio:2.0.0
      options: --user 0:0
      volumes:
        - /home/buildbot/.ssh:/root/.ssh
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
      - name: Install Library with PlatformIO
        run: pio pkg install -g -l file://.
      - name: Build example
        run: pio ci --board=esp32dev examples/platform_io_example.ino
concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true
